### PR TITLE
Allow Aulib::init on a specified device

### PR DESCRIPTION
**Pull request by glebm**

### CODE REVIEW

**Comment by realnc** [comment]
Let's just use `const std::string&` for this instead of `char*`.

**Comment by glebm** [comment]
The underlying API and the querying method both accept `char *`, so this would just be an unnecessary conversion, no?

**Comment by realnc** [comment]
The underlying API is C, the API we provide is C++, so `std::string` makes the most sense here. If this was anything where performance matters, we would instead provide an overload for `const char*` as well. But it's just the `init()` functions. It's not gonna get called in a tight loop or anything :)

**Comment by glebm** [comment]
Fair enough

**Comment by glebm** [comment]
what's a nullptr string?

**Comment by realnc** [comment]
> what's a nullptr string?

There is none, but just use an empty string in those cases. So:

```
const std::string& device = {}
```

Then check if it's empty of course and pass `nullptr` to SDL if it is.

**Comment by glebm** [comment]
I guess this assumes we can never have an empty string device name?

**Comment by glebm** [comment]
oh well, could also be an `std::optional<std::string>` but that's not available in GCC 6 (well there is `std::experimental::optional`)

**Comment by glebm** [comment]
Done

**Comment by realnc** [comment]
I'm not aware that it's possible for a device name to be empty. Could be wrong of course, but that would be rather weird?

**Comment by glebm** [comment]
Yeah probably not a use case that's super important to support even if it does happen

**Pull request merged**
